baseUrl: http://localhost:8080
port: 8080

mysql:
  host: localhost
  port: 3306
  db: gin_login_register
  user: root
  password: root
  timeout: 10s

jwt:
  key: W9kUz9hmLpFBbbLcas
  accessAge: 1
  refreshAge: 3
